name: Terraform Deployment - Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9

      - name: Deploy Azure Resources - Prod
        run: |
          cd terraform/modules
          terraform init
          terraform apply -auto-approve
        env:
          TF_VAR_databricks_host: ${{ secrets.DATABRICKS_HOST_PROD }}
          TF_VAR_databricks_token: ${{ secrets.DATABRICKS_TOKEN_PROD }}
          TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID_PROD }}
          TF_VAR_resource_group_name: ${{ secrets.RESOURCE_GROUP_NAME_PROD }}
